### ISSUE TITLE
send_Keys() not working for flutter app in Appium with python

### ISSUE THREAD

**Issue by vaibhavdatir** [appium-flutter-driver/appium-flutter-driver#112]
When i try to enter some text into the text box i received error. I used send_Keys() also setvalue. but when i used click() its working.
I also try click() and then send_keys().

Error Message is

selenium.common.exceptions.InvalidElementStateException: Message: Cannot set the element to 'some text'. Did you interact with the correct element?

**Comment by nandhini0761** [comment]
@vaibhavdatir Appium send_keys won’t work if Any animations available in your Testing app.  We can able to achieve using runUnsynchronized() method. This method available in flutterdriver but it’s not available   appium flutter driver.

**Comment by vaibhavdatir** [comment]
Thank You @nandhini0761

**Comment by shibupanda** [comment]
@vaibhavdatir please attach the complete logs using GIST.

**Comment by vaibhavdatir** [comment]
@shibupanda  a link for complete log 

https://gist.github.com/vaibhavdatir/c0ed76a48b0f89eba91856a1bc55473a.js"

Error Message is selenium.common.exceptions.InvalidElementStateException: Message: Cannot set the element to 'example@example.com'. Did you interact with the correct element?

**Comment by KazuCocoa** [comment]
the log seems not flutter-driver. (The app under test was flutter app tho)
