### ISSUE TITLE
flutter application quit immediately after opened on ios real device

### ISSUE THREAD

**Issue by k19810703** [appium-flutter-driver/appium-flutter-driver#133]
when I run my test against ios real device , my flutter application quit immediately after it was opened.
appium version 1.20.1

appium log
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","deviceName":"HD-iphone","platformVersion":"14.3","app":"/Users/wuhuidong/Downloads/digitalapp-ita-debug.ipa","automationName":"Flutter","noReset":true,"retryBackoffTime":30000,"xcodeOrgId":"my org id","xcodeSigningId":"iPhone Developer","udid":"my udid"},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","deviceName":"HD-iphone","platformVersion":"14.3","app":"/Users/wuhuidong/Downloads/digitalapp-ita-debug.ipa","automationName":"Flutter","noReset":true,"retryBackoffTime":30000,"xcodeOrgId":"my org id","xcodeSigningId":"iPhone Developer","udid":"my udid"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","deviceName":"HD-iphone","platformVersion":"14.3","app":"/Users/wuhuidong/Downloads/digitalapp-ita-debug.ipa","automationName":"Flutter","noReset":true,"retryBackoffTime":30000,"xcodeOrgId":"my org id","xcodeSigningId":"iPhone Developer","udid":"my udid"},null,{"alwaysMatch":{"platformName":"iOS","deviceName":"HD-iphone","platformVersion":"14.3","app":"/Users/wuhuidong/Downloads/digitalapp-ita-debug.ipa","automationName":"Flutter","noReset":true,"retryBackoffTime":30000,"xcodeOrgId":"my org id","xcodeSigningId":"iPhone Developer","udid":"my udid"},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1611727530900 (14:05:30 GMT+0800 (GMT+08:00))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   deviceName
[BaseDriver]   platformVersion
[BaseDriver]   app
[BaseDriver]   automationName
[BaseDriver]   noReset
[BaseDriver]   retryBackoffTime
[BaseDriver]   xcodeOrgId
[BaseDriver]   xcodeSigningId
[BaseDriver]   udid
[Appium] Appium v1.20.1 creating new FlutterDriver (v0.0.25) session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "platformName": "iOS",
[debug] [BaseDriver]   "deviceName": "HD-iphone",
[debug] [BaseDriver]   "platformVersion": "14.3",
[debug] [BaseDriver]   "app": "/Users/wuhuidong/Downloads/digitalapp-ita-debug.ipa",
[debug] [BaseDriver]   "automationName": "Flutter",
[debug] [BaseDriver]   "noReset": true,
[debug] [BaseDriver]   "retryBackoffTime": 30000,
[debug] [BaseDriver]   "xcodeOrgId": "my org id",
[debug] [BaseDriver]   "xcodeSigningId": "iPhone Developer",
[debug] [BaseDriver]   "udid": "my udid"
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   xcodeOrgId
[BaseDriver]   xcodeSigningId
[BaseDriver] Session created with session id: 3167dee2-523e-4ce0-9762-900f514f8c30
[FlutterDriver] Starting an IOS proxy session
[debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
[debug] [BaseDriver]   "platformName": "iOS",
[debug] [BaseDriver]   "deviceName": "HD-iphone",
[debug] [BaseDriver]   "platformVersion": "14.3",
[debug] [BaseDriver]   "app": "/digitalapp-ita-debug.ipa",
[debug] [BaseDriver]   "automationName": "Flutter",
[debug] [BaseDriver]   "noReset": true,
[debug] [BaseDriver]   "retryBackoffTime": 30000,
[debug] [BaseDriver]   "xcodeOrgId": "my xcodeOrgId",
[debug] [BaseDriver]   "xcodeSigningId": "iPhone Developer",
[debug] [BaseDriver]   "udid": "my udid",
[debug] [BaseDriver]   "newCommandTimeout": 0
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   retryBackoffTime
[BaseDriver] Session created with session id: 7470c0c0-e1fa-4c56-9ff6-e0351db21c13
[debug] [XCUITest] Current user: 'wuhuidong'
[debug] [XCUITest] Available devices: my udid
[debug] [XCUITest] Creating iDevice object with udid 'my udid'
[XCUITest] Determining device to run tests on: udid: 'my udid', real device: true
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1611727530930 (14:05:30 GMT+0800 (GMT+08:00))
[BaseDriver] Using local app '/Users/wuhuidong/Downloads/digitalapp-ita-debug.ipa'
[BaseDriver] Will reuse previously cached application at '/var/folders/kx/7kmn9ss168bcx526cfsggf9c0000gn/T/2021027-69554-sz9uob.stu3g/Runner.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1611727531048 (14:05:31 GMT+0800 (GMT+08:00))
[debug] [XCUITest] Checking whether app '/var/folders/kx/7kmn9ss168bcx526cfsggf9c0000gn/T/2021027-69554-sz9uob.stu3g/Runner.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/kx/7kmn9ss168bcx526cfsggf9c0000gn/T/2021027-69554-sz9uob.stu3g/Runner.app': 'jp.co.xxxxbank.digitalapp.ita'
[debug] [BaseDriver] Event 'resetStarted' logged at 1611727531049 (14:05:31 GMT+0800 (GMT+08:00))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1611727531049 (14:05:31 GMT+0800 (GMT+08:00))
[WebDriverAgent] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1611727531647 (14:05:31 GMT+0800 (GMT+08:00))
[XCUITest] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[debug] [XCUITest] App 'jp.co.xxxxbank.digitalapp.ita' is already installed. No need to reinstall.
[debug] [BaseDriver] Event 'appInstalled' logged at 1611727531935 (14:05:31 GMT+0800 (GMT+08:00))
[debug] [WebDriverAgent] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device my udid on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 1
[DevCon Factory] Found cached connections on port #8100: ["my udid:8100"]
[DevCon Factory] Port #8100 is busy. Did you quit the previous driver session(s) properly?
[DevCon Factory] Trying to release the port
[DevCon Factory] Releasing the listener for 'my udid:8100'
[debug] [iProxy@00008020:8100] Closing the connection
[DevCon Factory] Port #8100 has been successfully released after 5ms
[DevCon Factory] Successfully requested the connection for my udid:8100
[debug] [WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/wuhuidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Build/Products'
[debug] [WebDriverAgent] Got derived data root: '/Users/wuhuidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [XCUITest] Starting WebDriverAgent initialization with the synchronization key '/Users/wuhuidong/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.2","version":"14.3"},"ios":{"ip":"9.197.67.176"},"ready":true,"build":{"upgradedAt":"1610590710322","time":"Jan 25 2021 23:51:05","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"1A54338D-2E60-4BFA-A21E-0B8F658E63B4"}
[debug] [WebDriverAgent] Upgrade timestamp of the currently bundled WDA: 1610590710322
[debug] [WebDriverAgent] Upgrade timestamp of the WDA on the device: 1610590710322
[WebDriverAgent] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [XCUITest] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1611727536336 (14:05:36 GMT+0800 (GMT+08:00))
[WebDriverAgent] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"14.2","version":"14.3"},"ios":{"ip":"9.197.67.176"},"ready":true,"build":{"upgradedAt":"1610590710322","time":"Jan 25 2021 23:51:05","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"1A54338D-2E60-4BFA-A21E-0B8F658E63B4"}
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1611727536353 (14:05:36 GMT+0800 (GMT+08:00))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"jp.co.xxxxbank.digitalapp.ita","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}],"alwaysMatch":{}}}
[debug] [WD Proxy] Got response with status 200: {"value":{"sessionId":"48BBF6EB-1AF3-406F-9BDA-76BFC43233EB","capabilities":{"device":"iphone","browserName":"XXXXX","sdkVersion":"14.3","CFBundleIdentifier":"jp.co.xxxxbank.digitalapp.ita"}},"sessionId":"48BBF6EB-1AF3-406F-9BDA-76BFC43233EB"}
[WD Proxy] Determined the downstream protocol as 'W3C'
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1611727539356 (14:05:39 GMT+0800 (GMT+08:00))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1611727539357 (14:05:39 GMT+0800 (GMT+08:00))
[XCUITest] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [BaseDriver] Event 'orientationSet' logged at 1611727539360 (14:05:39 GMT+0800 (GMT+08:00))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1611727539401 (14:05:39 GMT+0800 (GMT+08:00))
[debug] [W3C] Encountered internal error running command: TypeError: Cannot read property 'match' of undefined
[debug] [W3C]     at Object.exports.processLogToGetobservatory (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/build/driver/lib/sessions/observatory.js:118:9)
[debug] [W3C]     at Object.exports.getObservatoryWsUri (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:30:21)
[debug] [W3C]     at Object.exports.startIOSSession (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/sessions/ios.ts:22:28)
[debug] [W3C]     at process._tickCallback (internal/process/next_tick.js:68:7)
[HTTP] <-- POST /wd/hub/session 500 8504 ms - 579
[HTTP]
[iProxy@00008020:8100] The connection has been closed
[iProxy@00008020:8100] The connection has been closed
[iProxy@00008020:8100] The connection has been closed

**Comment by KazuCocoa** [comment]
v0.0.25 did not work with iOS real devices. v0.0.29 could try out.
