### ISSUE TITLE
Unable to accept permission alert on iOS

### ISSUE THREAD

**Issue by thusithatab** [appium-flutter-driver/appium-flutter-driver#169]
I am trying to automate a Flutter-based iOS app with the Appium-flutter-driver on an iOS real device. In the initial screen of the app, there is a ‘Sign-in’ button and clicking on that, it opens a permission alert as it navigates to a web-based sign-in page. This alert has 'Cancel' and 'Continue' buttons and I want to click the 'Continue'. My script works fine until this alert but cannot get through this permission alert at the moment.

I have tried adding `autoGrantPermissions` and `autoAcceptAlerts` capabilities to the test but it didn’t work.

Is there a solution or workaround for this?

**Comment by KazuCocoa** [comment]
This flutter driver does not work for system element interactions.
https://github.com/truongsinh/appium-flutter-driver#todo

**Comment by teeencho** [comment]
Try this: 

```
let contexts = await driver.getContexts();
await driver.switchContext(contexts[0]);
await driver.pause(3000);
let allow = await $('~Continue');
await allow.click();
```
