### ISSUE TITLE
Unable to set mock location using flutter driver

### ISSUE THREAD

**Issue by vinaybalepur** [appium-flutter-driver/appium-flutter-driver#173]
I am automating a location based application, which needs me to simulate a particular location for the user. When I try to do this, I am getting an error as method not implemented. I am using set-location method provided by appium driver and looks like this method is not yet implemented in flutter driver. Can this option be provided as the same is available with uiautomation2 and iphone automation as well.

driver.setLocation(new Location(35.65880712797477, 139.7454597198317, 0.0)); -> Not yet implemented.

**Comment by KazuCocoa** [comment]
What about switching its context to `NATIVE_APP`?

**Comment by vinaybalepur** [comment]
Thank you @KazuCocoa . It is working now.
