### ISSUE TITLE
How to test on multi devices?

### ISSUE THREAD

**Issue by hbolin** [appium-flutter-driver/appium-flutter-driver#75]
When I test on multi devices. It throws the following error:
It looks like the error caused by FlutterDriver using “adb forward”.

```
[debug] [FlutterDriver] D:\Work\AndroidSDK\platform-tools\adb.exe forward tcp:40477 tcp:40477
[debug] [FlutterDriver] Deleting Flutter Driver session
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1586940481702 (16:48:01 GMT+0800 (GMT+08:00))
[debug] [W3C] Encountered internal error running command: Error: Command failed: D:\Work\AndroidSDK\platform-tools\adb.exe forward tcp:40477 tcp:40477
[debug] [W3C] adb.exe: error: more than one device/emulator
```

When I comment the following codes, It can run. But can't test flutter code
flutterCapabilities.setCapability ("automationName", "Flutter");

**Comment by shibupanda** [comment]
@hbolin 
Please share the complete logs using gist.

**Comment by jstephancc** [comment]
Hello,

I discovered the same issue. Here is my error message:
`[debug] [35m[W3C][39m Encountered internal error running command: Error: Command failed: /Users/jakubstephan/Library/Android/sdk/platform-tools/adb forward tcp:51006 tcp:51006
[debug] [35m[W3C][39m adb: error: more than one device/emulator`

I looks like a problem with this function: https://github.com/truongsinh/appium-flutter-driver/blob/424a9fb38152b450c8bc0b35fbbccd7fa00e9b1b/driver/lib/sessions/android.ts#L34

I dont know why, but in my case, this command is executed without -s UDID parameter as it's wrote in the code.
I have 2 devices connected, but in capabilities i'm pointing into specific one by: udid, name, os_version.

In the attachment i have added also appium full log, with capabilities etc.
[appium.log](https://github.com/truongsinh/appium-flutter-driver/files/5873218/appium.log)

**Comment by shibupanda** [comment]
Thanks @jstephancc for reporting this. Strange thing is I am not able to see -s udid in the logs. Will try to reproduce the issue.
@hex0cter is it fine for you to reproduce this.

**Comment by jstephancc** [comment]
@shibupanda if you will be able to debug this code, please check if this function is called during this issue. It might be a issue, that method is called from appium-base instead of your implementation ?

Please let me know, can i help you somehow ?

**Comment by shibupanda** [comment]
> @shibupanda if you will be able to debug this code, please check if this function is called during this issue. It might be a issue, that method is called from appium-base instead of your implementation ?
> 
> Please let me know, can i help you somehow ?

If you can build the driver locally by adding some logs after https://github.com/truongsinh/appium-flutter-driver/blob/424a9fb38152b450c8bc0b35fbbccd7fa00e9b1b/driver/lib/sessions/android.ts#L36 and check if the udid is getting printed.

**Comment by jstephancc** [comment]
@shibupanda will you be able to give some short instruction how to make it ?

I guess after cloning repo, i need to go inside driver dir and process there prepare & compile scripts?
Then should i move build dir into my path where global node_modules are stored? Or there is some easiest way to use locally build package ?
I'm working on OSX.

**Comment by shibupanda** [comment]
> @shibupanda will you be able to give some short instruction how to make it ?
> 
> I guess after cloning repo, i need to go inside driver dir and process there prepare & compile scripts?
> Then should i move build dir into my path where global node_modules are stored? 

Yes inside appium-flutter-driver

**Comment by hex0cter** [comment]
@jstephancc this is how I tested it locally:

* clone the repo
* go to the **driver** folder
* run `npm link`
* Find out where you appium is installed (different for command line and appium desktop). In my case `which appium` suggests it is installed `~/.nvm/versions/node/v12.16.2/bin/appium`. Based on that I can tell the appium-flutter-driver is in `~/.nvm/versions/node/v12.16.2/lib/node_modules/appium/node_modules/appium-flutter-driver`
* run `rm -r ~/.nvm/versions/node/v12.16.2/lib/node_modules/appium/node_modules/appium-flutter-driver`
* create a symbolic file `ln -s <repo path>/driver ~/.nvm/versions/node/v12.16.2/lib/node_modules/appium/node_modules/appium-flutter-driver`
* Next time you run the tests, appium should pick up what you have locally.

Hope this helps.

**Comment by jstephancc** [comment]
Hi,

I have some problem with running my version of appium-flutter-driver.

I removed `rm -r /usr/local/lib/node_modules/appium-flutter-driver`

I have project cloned into:
`/Users/jakubstephan/dev/appium-flutter-driver`

I have run there a command `npm link`:
```
MacBook-Pro-Jakub:driver jakubstephan$ npm link

> appium-flutter-driver@0.0.27 prepare /Users/jakubstephan/dev/appium-flutter-driver/driver
> npm run clean && npm run compile


> appium-flutter-driver@0.0.27 clean /Users/jakubstephan/dev/appium-flutter-driver/driver
> rm -rf build


> appium-flutter-driver@0.0.27 compile /Users/jakubstephan/dev/appium-flutter-driver/driver
> tsc

audited 629 packages in 4.614s

26 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
/usr/local/lib/node_modules/appium-flutter-driver -> /Users/jakubstephan/dev/appium-flutter-driver/driver
```

It looks like link is created (location: /usr/local/lib/node_modules/appium-flutter-driver):
`lrwxr-xr-x    1 jakubstephan  admin    52B 27 sty 08:11 appium-flutter-driver -> /Users/jakubstephan/dev/appium-flutter-driver/driver`

I have added some basic modification like:
```
logger.debug(`JS modification - Executing Flutter driver command '${cmd}'`);
```

But there is no effect while running a tests...
`[debug] [FlutterDriver] Executing Flutter driver command 'implicitWait'`

**Comment by jstephancc** [comment]
Together with my team college we found an issue.

Problem is, that appium uses appium-flutter-driver from:
`/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver`

i had also appium-flutter-driver installed in latest version but in:
`/usr/local/lib/node_modules/appium-flutter-driver`

And...
`/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver` - verision 0.0.23
`/usr/local/lib/node_modules/appium-flutter-driver` - verision 0.0.27

Fix/change for it is already in place:
https://github.com/truongsinh/appium-flutter-driver/commit/813dd31d562fa1b58fb7af310641b2ac75a5051b#diff-2d098b30480f3d2c04ff2e94d5b06d801d2df603df05e8d5ac7fb4d798621bb8R42

I guess problem is, that appium has older version of appium-flutter-driver by default.

**Comment by hex0cter** [comment]
I was going to ask the same question. But maybe it is a question for Appium?

**Comment by shibupanda** [comment]
@hex0cter @jstephancc that should not be the case because "appium-flutter-driver": "^0" mentioned in appium package.json so it should pick latest one started with 0.*.* until will release a major version.
https://github.com/appium/appium/blob/d37090e67e88d2f59113b62174f1dcd1d2e8611f/package.json#L48

**Comment by hex0cter** [comment]
I just double checked that:
appium@1.20.2 -> appium-flutter-driver@0.0.25
appium@1.20.0-beta.0 -> appium-flutter-driver@0.0.27

As of today when we install appium by `npm install -g appium`, by default appium@1.20.2 is installed.

So I guess next release of appium will pick up appium-flutter-driver@0.0.27 and above.

**Comment by KazuCocoa** [comment]
Probably the next 1.21.0 will have the version

**Comment by hex0cter** [comment]
In case anyone wants to try the latest version, `appium@1.20.0-beta.0` already have `appium-flutter-driver@0.0.28`. https://david-dm.org/appium/appium
