### ISSUE TITLE
Disable to creation Session with native app with flutter module on real android device

### ISSUE THREAD

**Issue by rex-wong** [appium-flutter-driver/appium-flutter-driver#82]
### Description ###
Failing to make a connection by returning Encountered internal error running command: TypeError: Cannot read property 'match' of undefined from dart observatory

### Environment ###
Appium verison: 1.17.0
Android verison: 9.0.0

### Link to Appium log ###
https://github.com/rex-wong/appium_test_1589188767195/blob/master/appium_202005111735.log

**Comment by shibupanda** [comment]
@rex-wong 
Could you please try with 1.16.0 if possible and see if this issue is exists in this version.

**Comment by shibupanda** [comment]
cc @truongsinh

**Comment by rex-wong** [comment]
I've try with 1.16.0 which re-produce the result as same as 1.17.0 of session directly closed by exception of property of undefine is reached

**Environment**
Appium verison: 1.16.0
Android verison: 9.0.0

**Link to Appium log**
https://github.com/rex-wong/appium_test_1589188767195/blob/master/appium_202005120944.log

**Comment by shibupanda** [comment]
@rex-wong 
Are you using Appium CLI or Appium desktop server?

**Comment by rex-wong** [comment]
yes. it is using Appium CLI for the test.

**Comment by shibupanda** [comment]
Ok. Could you please send me the env details.
Dart and flutter version details.
Seems not reproducible for me.

**Comment by rex-wong** [comment]
**Information from flutter and Dart as below:**
Flutter 1.14.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (4 months ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

**Information shown from appium-doctor as below:**
info AppiumDoctor Appium Doctor v.1.13.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 12.8.1
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.34.0
info AppiumDoctor  ✔ HOME is set to: /Users/rexwong
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/rexwong/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Users/rexwong/.sdkman/candidates/java/current
info AppiumDoctor  ✔ adb exists at: /Users/rexwong/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/rexwong/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/rexwong/Library/Android/sdk/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ set-simulator-location is not installed
WARN AppiumDoctor  ✖ idb and idb_companion are not installed
WARN AppiumDoctor  ✖ applesimutils cannot be found
info AppiumDoctor  ✔ ios-deploy is installed at: /usr/local/bin/ios-deploy. Installed version is: 1.10.0
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 7 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/image-comparison.md
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ set-simulator-location is needed to set location for Simulator. Please real https://github.com/lyft/set-simulator-location to install it
WARN AppiumDoctor  ➜ Why idb is needed and how to install it: https://github.com/appium/appium-idb
WARN AppiumDoctor  ➜ Why applesimutils is needed and how to install it: http://appium.io/docs/en/drivers/ios-xcuitest/
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by rex-wong** [comment]
there's some updates about the environment setup that this side tried several real devices for test which some launch session in success and some launch in failure with the same result that I post at the beginning:

**Devices 2**
Samsung Note 9
Android version: 9
Test Result: Success

**Devices 3**
Huawei Y9
Android version: 9
Test Result: Failure

**Devices 1**
LG Q6 PLus
Android version: 7.1.1
Test Result: Failure

According to the above findings. It is believed that such issue may device specific or device brand specific. Hope such finding will help.

**Comment by pripriya2** [comment]
Is their any fix for this ? Please help as its blocking me to proceed further

**Comment by ravijha-adi** [comment]
could anyone provide the working configuration for java. example - used appium version, appium-flutter-driver version, android version, maven version etc

**Comment by pripriya2** [comment]
You can Use:
@ravijha-adi 
appium 1.16.0
Samsung S9 OS version: 9
On running flutter doctor:
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[!] Android Studio (not installed)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

NOTE: You can take latest Flutter version.
NOTE: appium-flutter-driver is inbuilt in appium 1.16 (1.17.0 dint work at all for me)

**Comment by pripriya2** [comment]
> could anyone provide the working configuration for java. example - used appium version, appium-flutter-driver version, android version, maven version etc
> I tried downgrading appium but still facing the same issue Cannot read property 'match' of undefined from dart observatory

Your Issue looks more of a dev Issue.
Reason: developer needs to add support for Flutter automation in their code.
In the main.dart file of thier app before calling main() they need to call enableFlutterDriverExtension();
https://developer.aliyun.com/mirror/npm/package/appium-flutter-driver

**Comment by shibupanda** [comment]
Hi @rex-wong @pripriya2 please check 
https://github.com/truongsinh/appium-flutter-driver/issues/91

As per the analysis it needs to add below permission in app. Please try and let us know
<uses-permission android:name="android.permission.INTERNET"/>

**Comment by davidjohnmaccallum** [comment]
I ran into this issue and solved it as follows:

1. Add enableFlutterDriverExtension() call before runApp().
1. Ensure that APK was built in debug mode. I did this using `flutter run`. DONT use `flutter build` to create the APK.

**Comment by sahanaprasad** [comment]
I have added the permission and still facing the issue. @shibupanda @davidjohnmaccallum. Can someone tell me how this issue can be resolved?

**Comment by KazuCocoa** [comment]
Afaik, ` Cannot read property 'match' of undefined` occurs when appium-flutter-driver failed to find a device and its logcat.
e.g. a host which has multiple android devices. In the case, 0.0.29 should work.

**Comment by Harsha-Gelato** [comment]
@jstephancc Did it solve for you? I have been stuck on this for sometime and not getting any further.

Any help will be appreciated.
