### ISSUE TITLE
What's stopping the requestData method from being implemented?

### ISSUE THREAD

**Issue by romariochinloy** [appium-flutter-driver/appium-flutter-driver#90]
I understand that the webview testing is blocked because of a missing implementation in flutter_driver, so I am unable to test my login, one solution is to mock the login using DataHandler in flutter which requires the use of `requestData`.

**Comment by shibupanda** [comment]
PRs are welcome.

**Comment by yanivamram** [comment]
Hey,
I have the fix for this issue
But I don't have the required permissions to create a branch and PR.
Pls grant the permissions and I will share the PR..

Thanks,
Yaniv
