### ISSUE TITLE
appium_flutter_finder throws exception in ruby - when trying to start_driver

### ISSUE THREAD

**Issue by Manojv00087** [appium-flutter-driver/appium-flutter-driver#99]
![image](https://user-images.githubusercontent.com/46107289/92323932-4430e780-f05a-11ea-8384-e911f4d07a7a.png)

When I'm trying to start_driver itself - I'm facing this error. Did I miss something?

I have added appium_flutter_finder dependencies and finding element by Appium::Flutter::Element only. I'm not sure what I might have missed in the config. Can someone help on this?

**Comment by baovu2512** [comment]
do you enableFlutterDriverExtension() in your main.dart ?

**Comment by Manojv08** [comment]
@baovu2512 - I'm actually using this dependency for a test automation project and we don't use main.dart file in our project.. Is that Mandatory to create that sort of file in our rspec ruby project?

For reference - I was trying out this example from this repo - 
https://github.com/truongsinh/appium-flutter-driver/blob/master/example/ruby/example.rb

**Comment by baovu2512** [comment]
https://flutter.dev/docs/cookbook/testing/integration/introduction, enable driver in your app code

**Comment by Reppinger** [comment]
We put the `enableFlutterDriverExtension();` in the main of app_test.dart in the test_driver folder. When we want to run cucumber tests, we first run `flutter drive --target=test_driver/app.dart`.

We don't have an flutter driver tests, but this compiles the debug version of the app with the extensions enabled and then Appium_flutter_driver can connect.

I wouldn't enable flutter driver extension in my production code, personally.
